# Generated by Django 5.2.4 on 2026-02-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course_batch',
            new_name='academic_batch',
        ),
        migrations.AddField(
            model_name='student',
            name='file_batch',
            field=models.CharField(default='A', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=10),
        ),
    ]
