# Generated by Django 5.2.4 on 2026-02-13 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_projectgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectgroup',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.faculty'),
        ),
    ]
