# Generated by Django 5.2.4 on 2026-02-13 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_remove_student_faculty_student_project_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='project_group',
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='students',
            field=models.ManyToManyField(to='Admin.student'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.faculty'),
        ),
    ]
