# Generated by Django 5.2.4 on 2026-02-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_remove_student_project_group_projectgroup_students_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectGroup',
        ),
    ]
