# Generated by Django 5.2.4 on 2026-02-15 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_delete_projectgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Admin.faculty')),
                ('students', models.ManyToManyField(to='Admin.student')),
            ],
        ),
    ]
