# Generated by Django 5.2.4 on 2026-02-15 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_alter_admin_created_at_projectgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroup',
            name='group_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.faculty'),
        ),
    ]
