# Generated by Django 5.2.4 on 2026-02-16 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_reviewschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('proposal', 'Proposal'), ('progress', 'Progress Report'), ('final', 'Final Report'), ('presentation', 'Presentation Slides')], max_length=50)),
                ('description', models.TextField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('allowed_file_type', models.CharField(default='pdf', max_length=20)),
                ('max_file_size', models.IntegerField(default=10)),
                ('max_attempts', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('attempt_number', models.IntegerField(default=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.student')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.submissionschedule')),
            ],
        ),
    ]
