# Generated by Django 5.2.4 on 2026-02-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_submissionschedule_documentsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentsubmission',
            name='attempt_number',
        ),
        migrations.AddField(
            model_name='documentsubmission',
            name='mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
