# Generated by Django 5.2.4 on 2026-02-19 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_remove_documentsubmission_attempt_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionschedule',
            name='max_attempts',
        ),
    ]
