# Generated by Django 5.2.4 on 2026-03-13 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_reviewmark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewMark',
        ),
    ]
