# Generated by Django 5.2.4 on 2026-03-14 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_delete_reviewmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentsubmission',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='documentsubmission',
            name='student',
        ),
        migrations.DeleteModel(
            name='SubmissionSchedule',
        ),
        migrations.DeleteModel(
            name='DocumentSubmission',
        ),
    ]
