# Generated by Django 5.2.4 on 2026-03-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0018_remove_documentsubmission_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('file_format', models.CharField(max_length=50)),
                ('max_size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
