# Generated by Django 5.2.4 on 2026-03-13 05:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_delete_reviewmark'),
        ('faculty', '0002_remove_attendance_faculty_attendance_faculty_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.reviewschedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.student')),
            ],
            options={
                'unique_together': {('review', 'student')},
            },
        ),
    ]
