# Generated by Django 5.2.4 on 2026-03-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsubmission',
            name='faculty_mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
