# Generated by Django 5.2.4 on 2026-03-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_documentsubmission_faculty_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsubmission',
            name='faculty_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
